### ISSUE TITLE
Css styly v html komponente

### ISSUE THREAD

**Issue by katarinaHrab** [gachojuraj/AngularExercises#1]
https://github.com/gachojuraj/AngularExercises/blob/da28146a7b73014134145dbd665df0f737066b43/src/app/item-detail/item-detail.component.html#L2

Lepsie je davat css pravidla do css suboru a v pripade, ze potrebujes specialne nieco upravit tak pouzit css id alebo class. Zatial mas v html toho malo, ale ked sa to bude rozsirovat, tak sa to lahko zneprehladni.

**Comment by gachojuraj** [comment]
fixed (more will be fixed soon)
https://github.com/gachojuraj/AngularExercises/blob/d7afdfb7107084d69ff11f5c605086be5e03c861/src/app/item-detail/item-detail.component.html#L2
