### ISSUE TITLE
Spravne poradie casti kodu

### ISSUE THREAD

**Issue by katarinaHrab** [gachojuraj/AngularExercises#2]
https://github.com/gachojuraj/AngularExercises/blob/da28146a7b73014134145dbd665df0f737066b43/src/app/items/items.component.ts#L57

Jednotlive casti kodu maju zauzivane poradie, tj. vsetky globalne premenne v triede/komponente su pokope spisane za sebou pred funkciami. A az potom idu funkcie. Tu mas hero schovane medzi funkciami ;)

**Comment by gachojuraj** [comment]
fixed (more code cleanup coming soon)
https://github.com/gachojuraj/AngularExercises/blob/d7afdfb7107084d69ff11f5c605086be5e03c861/src/app/items/items.component.ts#L17
