### ISSUE TITLE
Zvlast metoda pre createForm a obalenie fieldov do FormGroup

### ISSUE THREAD

**Issue by katarinaHrab** [gachojuraj/AngularExercises#4]
https://github.com/gachojuraj/AngularExercises/blob/392ca0212d983db320e3c9099312f815430ffeff/src/app/hero-form/hero-form.component.ts#L18

Nepaci sa mi moc tato inicializacia pri deklarovani atributov. Moze nastat aj pripad, ze budes potrebovat vytvorit formular na novo, ci uz kvoli premazaniu fieldov alebo nieco podobne. Pride mi lepsie mat zvlast metodu createForm, v ktorej vytvorit FormGroup a vramci nej jednotlive fieldy formulara, napr. 
private createForm() {
    this.createHeroForm = this.fb.group({
         ... //inicializacia jednotlivych policok
     });
}

**Comment by gachojuraj** [comment]
fixed
https://github.com/gachojuraj/AngularExercises/blob/882e93e3e3315cfee1109ced4ace266eeb470168/src/app/hero-form/hero-form.component.ts#L20-L28
