### ISSUE TITLE
Malo by stacit ngIf*=this.heroes bez porovnania s undefined

### ISSUE THREAD

**Issue by katarinaHrab** [gachojuraj/AngularExercises#5]
https://github.com/gachojuraj/AngularExercises/blob/392ca0212d983db320e3c9099312f815430ffeff/src/app/heroes/heroes.component.html#L33

**Comment by gachojuraj** [comment]
fixed
https://github.com/gachojuraj/AngularExercises/blob/882e93e3e3315cfee1109ced4ace266eeb470168/src/app/heroes/heroes.component.html#L33
